export const queries = [
  "INSERT INTO  tbl_category (category_Id,category_Name) VALUES ('CAT1','Cake')",
  "INSERT INTO  tbl_category (category_Id,category_Name) VALUES ('CAT2','No-Bake')",
  "INSERT INTO  tbl_category (category_Id,category_Name) VALUES ('CAT3','Vegetarian')",
  "INSERT INTO  tbl_category (category_Id,category_Name) VALUES ('CAT4','Vegan')",
  "INSERT INTO  tbl_category (category_Id,category_Name) VALUES ('CAT5','Gluten-Free')",
  "INSERT INTO  tbl_category (category_Id,category_Name) VALUES ('CAT6','Japanese')",

  "INSERT INTO  tbl_unit_list(unit_Id,unit_Description) VALUES ('gr','Gram')",
  "INSERT INTO  tbl_unit_list(unit_Id,unit_Description) VALUES ('kg','Kilogram')",
  "INSERT INTO  tbl_unit_list(unit_Id,unit_Description) VALUES ('lt','Liter')",
  "INSERT INTO  tbl_unit_list(unit_Id,unit_Description) VALUES ('ml','Milliliter')",
  "INSERT INTO  tbl_unit_list(unit_Id,unit_Description) VALUES ('pc','Piece')",

  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F001','Condensed milk',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F002','Cream Cheese',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F003','Lemon Juice',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F004','Pie Crust',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F005','Cherry Jam',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F006','Brussels Sprouts',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F007','Sesame seeds',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F008','Pepper',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F009','Salt',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F010','Olive oil',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F011','Macaroni',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F012','Butter',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F013','Flour',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F014','Milk',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F015','Shredded Cheddar cheese',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F016','Egg',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F017','Soy sauce',1)",
  "INSERT INTO  tbl_food_list(food_Id,food_Desc,is_Available) VALUES ('F018','Sugar',1)",

  "INSERT INTO  tbl_recipe(recipe_Id,recipe_Description,recipe_Created_Date,category1_Id,category2_Id,category3_Id,servings_Number) VALUES ('REC001','No-Bake Cheesecake','2022-08-20','CAT1','CAT2','CAT3',4)",
  "INSERT INTO  tbl_recipe(recipe_Id,recipe_Description,recipe_Created_Date,category1_Id,category2_Id,category3_Id,servings_Number) VALUES ('REC002','Roasted Brussels Sprouts','2022-08-20','CAT4','CAT5',NULL,4)",
  "INSERT INTO  tbl_recipe(recipe_Id,recipe_Description,recipe_Created_Date,category1_Id,category2_Id,category3_Id,servings_Number) VALUES ('REC003','Mac and Cheese','2022-05-01','CAT3',NULL,NULL,5)",
  "INSERT INTO  tbl_recipe(recipe_Id,recipe_Description,recipe_Created_Date,category1_Id,category2_Id,category3_Id,servings_Number) VALUES ('REC004','Tamagoyaki Japanese Omelette','2022-04-02','CAT3','CAT6',NULL,6)",

  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING001','REC001','F001','lt',1)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING002','REC001','F002','gr',300)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING003','REC001','F003','ml',20)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING004','REC001','F004','gr',500)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING005','REC001','F005','gr',100)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING006','REC002','F006','gr',500)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING007','REC002','F003','ml',30)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING008','REC002','F007','gr',50)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING009','REC002','F008','gr',10)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING010','REC002','F009','gr',15)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING011','REC002','F010','ml',30)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING012','REC003','F011','gr',500)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING013','REC003','F012','gr',100)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING014','REC003','F013','gr',200)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING015','REC003','F009','gr',20)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING016','REC003','F008','gr',10)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING017','REC003','F014','ml',300)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING018','REC003','F015','gr',250)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING019','REC004','F016','pc',3)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING020','REC004','F017','ml',20)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING021','REC004','F018','gr',100)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING022','REC004','F009','gr',10)",
  "INSERT INTO  tbl_ingredient_records(record_Id,recipe_Id,food_Id,unit_Id,amount) VALUES ('ING023','REC004','F010','ml',50)",

  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP001','REC001',1,'Beat Cream Cheese',1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP002','REC001',2,'Add condensed Milk and blend',2);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP003','REC001',3,'Add Lemon Juice and blend',1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP004','REC001',4,'Add the mix to the pie crust',3);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP005','REC001',5,'Spread the Cherry Jam',2);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP006','REC001',6,'Place in refrigerator for 3h.',180);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP007','REC002',1,'Preheat the oven',10);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP008','REC002',2,'Mix the ingredients in a bowl',3);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP009','REC002',3,'Spread the mix on baking sheet',5);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP010','REC002',4,'Bake for 30 min',30);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP011','REC004',1,'Beat the eggs',3);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP012','REC004',2,'Add soya sauce, sugar and salt',1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP013','REC004',3,'Add oil to a sauce pan',1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP014','REC004',4,'Bring to medium heat',1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP015','REC004',5,'Add some mix to the sauce pan',1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP016','REC004',6,'Let is cook for 1 min',1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP017','REC004',7,'Add oil to a sauce pan',1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP018','REC004',8,'Add some mix to the sauce pan',1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP019','REC004',9,'Let is cook for 1 min',1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP020','REC004',10,'Remove pan from fire',1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP021','REC003',1,'Cook Macaroni for 8 min',8);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP022','REC003',2,'Melt butter in a saucepan',5);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP023','REC003',3,'Add flour, salt, pepper and mix' ,1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP024','REC003',4,'Add Milk and mix',2);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP025','REC003',5,'Cook until mix is smooth',10);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP026','REC003',6,'Add cheddar cheese',1);",
  "INSERT INTO tbl_step_records (record_Id,recipe_Id,step_Seq_No,step_Definition,step_Duration_Min) VALUES ('STP027','REC003',7,'Add the macaroni',1);",
];
